apiVersion: v1
kind: Pod

metadata:
  name: init-demo

spec:

  initContainers:
  - name: init-container
    image: busybox:latest
    command:
    - sh
    - -c
    - echo "Preparing application..." && sleep 5 && echo "Preparation completed"

  containers:
  - name: nginx
    image: nginx:latest
